# Site settings
timezone: America/Vancouver

baseurl: '/2018' # the subpath to the year of conference
url: 'https://expressivegraphics.github.io' # the base hostname & protocol for your site
# url: 'http://localhost:4000'

title: 'Expressive 2018'
author: 'Santiago Montesdeoca, Amir Semmo'

google_font_sans_serif: 'Source+Sans+Pro:300'

flickr_user: '131006004@N06'
flickr_api_key: adb4be93419edab991522b4fa92b7029

# Handling Reading
safe: true
encoding: utf-8
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Build settings
permalink: /:categories/:title/
markdown: kramdown

# Defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"
      schema: NewsArticle
      comments: true
      share: true
      image:
        card: 2018/expressiveCard.jpg

# Outputting
exclude: [
  'cibuild',
  'Gemfile',
  'Gemfile.lock',
  'package.json',
  'README.md',
  'vendor']

# CSS Minification
sass:
  style: compressed


# Symposium data
symposium:
  name: Expressive joint Symposium
  date: August 12-19, 2018
  location: Victoria, Canada
  URL: expressive.graphics/2018
  sponsors: ACM Siggraph, Eurographics and Adobe
  abstract: May 14, 2018
  paper: May 14, 2018
  acceptance: coming soon...
  disqus-shortname: expressiverendering
  twitter: ExpressiveGfx
  github: expressivegraphics
  google:
    analytics: UA-76809364-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:


# Conference chairs
chair2018:
  name: Brian Wyvill
