# Site settings
timezone: America/Vancouver

baseurl: '/2018' # the subpath to the year of conference
url: 'http://expressive.graphics' # the base hostname & protocol for your site
# url: 'http://localhost:4000'

title: 'Expressive 2018'
author: 'Santiago Montesdeoca, Amir Semmo, Daniel Limberger'

google_font_sans_serif: 'Source+Sans+Pro:300'

flickr_user: '131006004@N06'
flickr_api_key: adb4be93419edab991522b4fa92b7029

# Handling Reading
safe: true
encoding: utf-8
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Build settings
permalink: /:categories/:title/
markdown: kramdown

# Defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"
      schema: NewsArticle
      comments: true
      share: true
      image:
        card: 2018/expressiveCard.jpg

# Outputting
exclude: [
  'cibuild',
  'Gemfile',
  'Gemfile.lock',
  'package.json',
  'README.md',
  'vendor']

# CSS Minification
sass:
  style: compressed


# Symposium data
symposium:
  name: Expressive joint Symposium
  date: August 12-19, 2018
  location: Victoria, British Columbia, Canada
  URL: expressive.graphics/2018
  sponsors: ACM Siggraph, Eurographics, Disney Research and Adobe Research
  abstract: April 15, 2018
  paper: April 10, 2018
  extension: April 17, 2018
  acceptance: May 8, 2018
  camera-ready: June 5, 2018
  disqus-shortname: expressiverendering
  twitter: ExpressiveGfx
  github: expressivegraphics
  google:
    analytics: UA-76809364-1
    verify:
  bing-verify:
  submission: https://easychair.org/conferences/?conf=expressive180


# Conference chairs
chairs2018:
  general: Brian Wyvill
  generalAff: University of Victoria, Canada
  general2: Hongbo Fu
  general2Aff: City University of Hong Kong, Hong Kong
  paper: Tunç Aydın
  paperAff: Disney Research Zurich, Switzerland
  paper2: Daniel Sýkora
  paper2Aff: Czech Technical University in Prague, Czech Republic
  art: Jane Prophet
  artAff: University of London, United Kingdom
  publicity: Santiago Montesdeoca
  publicityAff: Nanyang Technological University, Singapore
  publicity2: Amir Semmo
  publicity2Aff: Hasso Plattner Institute, University of Potsdam, Germany
